language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get install python-fontforge
install: true
script:
  - python setup.py install
  - python /unittests/unittests.py
