# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fontCompare.ui'
#
# Created: Fri Jun  7 13:12:14 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(801, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 801, 561))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.groupBox_2 = QtGui.QGroupBox(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.groupBox = QtGui.QGroupBox(self.verticalLayoutWidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.groupBox)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(9, 29, 651, 241))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.groupBox_7 = QtGui.QGroupBox(self.horizontalLayoutWidget_3)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.horizontalLayout_3.addWidget(self.groupBox_7)
        self.groupBox_6 = QtGui.QGroupBox(self.horizontalLayoutWidget_3)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.horizontalLayout_3.addWidget(self.groupBox_6)
        self.groupBox_5 = QtGui.QGroupBox(self.horizontalLayoutWidget_3)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.horizontalLayout_3.addWidget(self.groupBox_5)
        self.horizontalLayout.addWidget(self.groupBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.groupBox_3 = QtGui.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.languageBox = QtGui.QComboBox(self.groupBox_3)
        self.languageBox.setGeometry(QtCore.QRect(10, 130, 85, 23))
        self.languageBox.setEditable(True)
        self.languageBox.setObjectName(_fromUtf8("languageBox"))
        self.languageBox.addItem(_fromUtf8(""))
        self.languageBox.addItem(_fromUtf8(""))
        self.languageBox.addItem(_fromUtf8(""))
        self.executeButton = QtGui.QPushButton(self.groupBox_3)
        self.executeButton.setGeometry(QtCore.QRect(290, 210, 95, 61))
        self.executeButton.setObjectName(_fromUtf8("executeButton"))
        self.loadTestpushButton = QtGui.QPushButton(self.groupBox_3)
        self.loadTestpushButton.setGeometry(QtCore.QRect(280, 30, 111, 31))
        self.loadTestpushButton.setObjectName(_fromUtf8("loadTestpushButton"))
        self.testfilepath = QtGui.QLabel(self.groupBox_3)
        self.testfilepath.setGeometry(QtCore.QRect(10, 30, 271, 20))
        self.testfilepath.setObjectName(_fromUtf8("testfilepath"))
        self.standardfilepath = QtGui.QLabel(self.groupBox_3)
        self.standardfilepath.setGeometry(QtCore.QRect(10, 70, 271, 20))
        self.standardfilepath.setObjectName(_fromUtf8("standardfilepath"))
        self.loadStandardpushButton = QtGui.QPushButton(self.groupBox_3)
        self.loadStandardpushButton.setGeometry(QtCore.QRect(280, 61, 111, 31))
        self.loadStandardpushButton.setObjectName(_fromUtf8("loadStandardpushButton"))
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(10, 110, 54, 13))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.pushButton = QtGui.QPushButton(self.groupBox_4)
        self.pushButton.setGeometry(QtCore.QRect(20, 250, 91, 22))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_2.setGeometry(QtCore.QRect(120, 250, 91, 22))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.MessageBox = QtGui.QTextBrowser(self.groupBox_4)
        self.MessageBox.setGeometry(QtCore.QRect(15, 30, 331, 211))
        self.MessageBox.setObjectName(_fromUtf8("MessageBox"))
        self.horizontalLayout_2.addWidget(self.groupBox_4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 801, 19))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menuE_dit = QtGui.QMenu(self.menubar)
        self.menuE_dit.setObjectName(_fromUtf8("menuE_dit"))
        self.menuHe_lp = QtGui.QMenu(self.menubar)
        self.menuHe_lp.setObjectName(_fromUtf8("menuHe_lp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_Font_File = QtGui.QAction(MainWindow)
        self.actionLoad_Font_File.setObjectName(_fromUtf8("actionLoad_Font_File"))
        self.actionSave_Test_Results = QtGui.QAction(MainWindow)
        self.actionSave_Test_Results.setObjectName(_fromUtf8("actionSave_Test_Results"))
        self.actionTest_Parameters = QtGui.QAction(MainWindow)
        self.actionTest_Parameters.setObjectName(_fromUtf8("actionTest_Parameters"))
        self.actionManual_Testing = QtGui.QAction(MainWindow)
        self.actionManual_Testing.setObjectName(_fromUtf8("actionManual_Testing"))
        self.menu_File.addAction(self.actionLoad_Font_File)
        self.menu_File.addAction(self.actionSave_Test_Results)
        self.menuE_dit.addAction(self.actionTest_Parameters)
        self.menuE_dit.addAction(self.actionManual_Testing)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menuE_dit.menuAction())
        self.menubar.addAction(self.menuHe_lp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Purpose of the Font", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Categorised Scores", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("MainWindow", "Glyph Consistency", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("MainWindow", "Readability and Print Proof", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("MainWindow", "Similarity to the Standards Set", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Control Box", None, QtGui.QApplication.UnicodeUTF8))
        self.languageBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "Devanagri", None, QtGui.QApplication.UnicodeUTF8))
        self.languageBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Bengali ", None, QtGui.QApplication.UnicodeUTF8))
        self.languageBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "English", None, QtGui.QApplication.UnicodeUTF8))
        self.executeButton.setText(QtGui.QApplication.translate("MainWindow", "Execute", None, QtGui.QApplication.UnicodeUTF8))
        self.loadTestpushButton.setText(QtGui.QApplication.translate("MainWindow", "Load Test File", None, QtGui.QApplication.UnicodeUTF8))
        self.testfilepath.setText(QtGui.QApplication.translate("MainWindow", "                        < Test File >", None, QtGui.QApplication.UnicodeUTF8))
        self.standardfilepath.setText(QtGui.QApplication.translate("MainWindow", "                        < Standard File >", None, QtGui.QApplication.UnicodeUTF8))
        self.loadStandardpushButton.setText(QtGui.QApplication.translate("MainWindow", "Load Standard File", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Script:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MainWindow", "Test Results", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Save To File", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("MainWindow", "Clear All", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuE_dit.setTitle(QtGui.QApplication.translate("MainWindow", "E&dit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHe_lp.setTitle(QtGui.QApplication.translate("MainWindow", "He&lp", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_Font_File.setText(QtGui.QApplication.translate("MainWindow", "Load Font File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Test_Results.setText(QtGui.QApplication.translate("MainWindow", "Save Test Results", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTest_Parameters.setText(QtGui.QApplication.translate("MainWindow", "Test Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.actionManual_Testing.setText(QtGui.QApplication.translate("MainWindow", "Manual Testing", None, QtGui.QApplication.UnicodeUTF8))

